function r = TestMutate()
  chromosome = [1 1 1 4 2 1 1 5 3 1 1 3 4 1 1 5].'
  probability = 0.0;
  numVariableRegisters = 2;
  numConstantRegisters = 1;
  numOperations = 4;
  r = Mutate(chromosome, ...
             probability, ...
             numVariableRegisters, ...
             numConstantRegisters, ...
             numOperations)
